version: "3"

services:
  app:
    image: dtriana/phplain
    ports:
      - "8000:8000"
    networks:
      - plain-external
    volumes:
      - .:/app
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure

networks:
  plain-external:
    external: true
