version: "3"
services:

  web:
    image: dtriana/nginx
    ports:
      - "8090:80"
    links:
      - php
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
        
  php:
    image: dtriana/phplain
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
        
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=password